### ISSUE TITLE
Do no work using internet explorer

### ISSUE THREAD

**Issue by babour** [FriendsOfSymfony/FOSFacebookBundle#103]
I can't login when I user internet eplorer, an other page opens and is empty.

**Comment by babour** [comment]
I looked a bit into the code and it seems, it's because of the window.location that doesn't work on internet explorer.
Even using the setTimeout trick (check on google) that used to work, it doesn't change anything... 

Anyone has solved this issue?

**Comment by babour** [comment]
You need to use the window.location.href function instead of window.location, and then it works

<script>
  function goLogIn(){
      window.location.href = "{{ path('_security_check') }}";
  }

  function onFbInit() {
      if (typeof(FB) != 'undefined' && FB != null ) {
          FB.Event.subscribe('auth.statusChange', function(response) {
              if (response.session || response.authResponse) {
                  setTimeout(goLogIn, 500);
              } else {
                  window.location.href = "{{ path('_security_logout') }}";
              }
          });
      }
  }
</script>

**Comment by lsmith77** [comment]
if you think it can help others, send a PR for an improvement to the README.md

**Comment by babour** [comment]
How? Can't find how to creqte one (I don't really know github), do I have to fork the repository?

**Comment by lsmith77** [comment]
Its even easier .. you can browse to the README.md and "click" edit:
https://github.com/FriendsOfSymfony/FOSFacebookBundle/blob/master/README.md

this will help you create a fork and a branch to submit as a PR

see also http://help.github.com/

**Comment by babour** [comment]
thx

**Comment by stof** [comment]
sent as #104 and merged
