### ISSUE TITLE
What Symfony2 version should I use ?

### ISSUE THREAD

**Issue by pierregoutheraud** [FriendsOfSymfony/FOSFacebookBundle#106]
Hi,

I'm using the master version of FOSFacebookBundle and FOSUserBundle.

I keep on having errors like :

Call to undefined method Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension::addSecurityListenerFactory() in MyWebAppPath\vendor\bundles\FOS\FacebookBundle\FOSFacebookBundle.php on line 25

or

Warning: require_once(C:\wamp\www\appName\app/../vendor/symfony/src/Symfony/Component/Locale/Resources/stubs/functions.php) [function.require-once]: failed to open stream: No such file or directory in C:\wamp\www\appName\app\autoload.php on line 26

Fatal error: require_once() [function.require]: Failed opening required 'C:\wamp\www\appName\app/../vendor/symfony/src/Symfony/Component/Locale/Resources/stubs/functions.php' (include_path='.;C:\php\pear') in C:\wamp\www\appName\app\autoload.php on line 26

I don't know if my errors are comming from my symfony version but i would like to be sure :
Which Symfony2 version should I use ? Which exact tag ?

Thank you, bye!

**Comment by stof** [comment]
The bundle has to branches: 2.0 is meant to be used with Symfony 2.0.x and master is meant to be used with Symfony master

**Comment by pierregoutheraud** [comment]
First of all thank you for your quick answer !

I have just tried with FOSFacebookBundle master, FOSUserBundle master and Symfony2 master and I have this error : 

Fatal error: Call to undefined method Symfony\Component\ClassLoader\DebugUniversalClassLoader::useIncludePath() in C:\wamp\www\website\vendor\symfony\src\Symfony\Component\ClassLoader\DebugUniversalClassLoader.php on line 41

What is wrong then ? :(

**Comment by stof** [comment]
you need to rebuild you bootstrap.php.cache file when changing your Symfony version (which should be done automatically when using the bin/vendors script)

**Comment by pierregoutheraud** [comment]
I'm sorry but I keep having this error...

Fatal error: Call to undefined method Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension::addSecurityListenerFactory() in C:\wamp\www\appName\vendor\bundles\FOS\FacebookBundle\FOSFacebookBundle.php on line 25

I am what we can call a beginner with symfony. I have never install any bundle before and I am actually a bit lost.

It seems like I didn't do the right thing when I tried to install Symfony master version. (Which is the version that I need if I want to use the master version of FOSFacebookBundle and FOSUserBundle, right ?)

Let's say I'm starting a new Symfony 2.0.9 projet.
Could someone take 10 minutes to explain how I should proceed to upgrade to Symfony master version and make this work, please ?

**Comment by lsmith77** [comment]
If your questions are not answered by http://symfony.com/doc/current/book/installation.html I would recommend to you to either send a question to the users mailing list, the forum or in #symfony on free node IRC. this ticket isn't really the right place, ok?

**Comment by pierregoutheraud** [comment]
I only want to know what I should do to make these bundles work... therefore I guess my question must be in the right place, Ismith77.
Don't you remember, back in the days, when you were a young developper ? Now you have the power to help me not waste hours on this problem. (and I already spent some on this!).

Whatever. Thank you

**Comment by lsmith77** [comment]
Installing Symfony2 master does not relate to this bundle. But yes, the master versions of the two noted bundles will work with Symfony2 master.

As for your implication that I don't care for your issue: I do, otherwise I would have ignored you. But if we keep answering such questions in random tickets, we will have to teach users one at a time, rather than teaching multiple people at a time. Our time to help beginners is limited.
