### ISSUE TITLE
vendor install failure -  undefined method ..addSecurityListenerFactory()

### ISSUE THREAD

**Issue by orangee** [FriendsOfSymfony/FOSFacebookBundle#108]
I cannot install the Bundle with the vendor script because FOSFacebookBundle.php calles the above method which does not exist at my installation.

I use Symfony 2.0.9

PHP Fatal error:  Call to undefined method Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension::addSecurityListenerFactory() in /home/lazafi/workspace/c4s/trunk/src/eenbaan/vendor/bundles/FOS/FacebookBundle/FOSFacebookBundle.php on line 25
PHP Stack trace:
PHP   1. {main}() /home/lazafi/workspace/c4s/trunk/src/eenbaan/app/console:0
PHP   2. Symfony\Component\Console\Application->run() /home/lazafi/workspace/c4s/trunk/src/eenbaan/app/console:22
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/lazafi/workspace/c4s/trunk/src/eenbaan/vendor/symfony/src/Symfony/Component/Console/Application.php:118
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() /home/lazafi/workspace/c4s/trunk/src/eenbaan/vendor/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:66
PHP   5. Symfony\Component\HttpKernel\Kernel->boot() /home/lazafi/workspace/c4s/trunk/src/eenbaan/vendor/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
PHP   6. Symfony\Component\HttpKernel\Kernel->initializeContainer() /home/lazafi/workspace/c4s/trunk/src/eenbaan/app/bootstrap.php.cache:513
PHP   7. Symfony\Component\HttpKernel\Kernel->buildContainer() /home/lazafi/workspace/c4s/trunk/src/eenbaan/app/bootstrap.php.cache:779
PHP   8. FOS\FacebookBundle\FOSFacebookBundle->build() /home/lazafi/workspace/c4s/trunk/src/eenbaan/app/bootstrap.php.cache:848

**Comment by lsmith77** [comment]
please use the 2.0 branch as noted in the README

**Comment by carbocation** [comment]
Minor note: the current README.md doesn't make any mention of the 2.0 branch. I discovered this thread after running into the same problem as orangee.

**Comment by lsmith77** [comment]
can you send a PR?

**Comment by brentc** [comment]
Just ran into this problem today. Indeed the README makes no mention of the 2.0 branch. Do you really need a PR to fix the README?

**Comment by lsmith77** [comment]
is to really so much to ask for someone else to fix this? :)
but actually what we need to do is actually finally add a composer.json (see https://github.com/FriendsOfSymfony/friendsofsymfony.github.com/issues/30) and "rename" the 2.0 branch (see https://github.com/FriendsOfSymfony/friendsofsymfony.github.com/issues/27)

but i must admit i am currently not really active on this Bundle .. maybe @kriswallsmith .. ?

**Comment by o10g** [comment]
Is it fixed?
I just installed bundle but got the same error. I did everything as described in Redme.md.
