### ISSUE TITLE
Problem with step6 of FOSFacebookBundle

### ISSUE THREAD

**Issue by Raulken** [FriendsOfSymfony/FOSFacebookBundle#117]
In step 6  of https://github.com/FriendsOfSymfony/FOSFacebookBundle/blob/master/README.md
say

Add this configuration if you want to use the security component
# application/config/config.yml

  security:
      firewalls:
          public:
              # since anonymous is allowed users will not be forced to login
              pattern:   ^/.*
              fos_facebook:
                  app_url: "http://apps.facebook.com/appName/"
                  server_url: "http://localhost/facebookApp/"
              anonymous: true
              logout:
                  handlers: ["fos_facebook.logout_handler"]

```
  access_control:
      - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
      - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
```

But this parameter i can set into config.yml or security.yml?
thx

**Comment by lsmith77** [comment]
yes .. its your choice if you want to define the security settings in a "security.yml" file that is included in the "config.yml" or if you do it directly inside the "config.yml"
