### ISSUE TITLE
Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken::serialize() must return a string or NULL

### ISSUE THREAD

**Issue by Raulken** [FriendsOfSymfony/FOSFacebookBundle#119]
this in user bundle give to me this error

User.php
public function serialize()
    {
        return serialize(array($this->facebookId, parent::serialize()));
    }

```
public function unserialize($data)
{
    list($this->facebookId, $parentData) = unserialize($data);
    parent::unserialize($parentData);
}
```

how i can fix?

**Comment by casoetan** [comment]
hey, have you fixed it / how did you fix it pls.
