### ISSUE TITLE
session changes in master

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSFacebookBundle#120]
we might also need to do some changes ..
see https://github.com/FriendsOfSymfony/FOSTwitterBundle/compare/30c39d8b21...95e1a92b00

**Comment by stof** [comment]
the typehint has already been changed. Other changes in the diff you linked are not related to the session changes but are a refactoring done by @schmittjoh in his own fork 4 months ago that were not submitted to the FOS repo

**Comment by schmittjoh** [comment]
yep, I've made the changes to FOSFB bundle already
