### ISSUE TITLE
Cannot install using composer

### ISSUE THREAD

**Issue by olegstepura** [FriendsOfSymfony/FOSFacebookBundle#127]
Hi!

After I add "friendsofsymfony/facebook-bundle": "dev-master" to my composer.json I cannot istall it

Composer ends up with exception

```
Updating dependencies

  [Composer\DependencyResolver\SolverProblemsException]
  [Job(cmd=install, target=friendsofsymfony/facebook-bundle, packages=[friendsofsymfony/facebook-bundle-9999999-dev]), ]
```

Other bundles work fine with composer so it must be a local configuration problem

**Comment by lsmith77** [comment]
you need to add the repository config from the FacebookBundle until Facebook as merged my PR and added the php sdk to packagist.org

**Comment by olegstepura** [comment]
Ok, FYI Twitterbundle is also not regitered on packagist.org

**Comment by lsmith77** [comment]
i have added it .. if there are issues open a ticket on the twitter bundle:
http://packagist.org/packages/friendsofsymfony/twitter-bundle

**Comment by ghost** [comment]
@olegstepura is everything good now? can you close this ticket?

**Comment by olegstepura** [comment]
Cannot tell, not using it now... I think you can test yourself or close if you already did.

**Comment by ghost** [comment]
@olegstepura  i'm not using this bundle yet .. i just thought i'd help triage a bit while i was browsing the issues. I have no access to close the issue only you or one of the repo owners can.

So can you close this then? i really doubt it is a problem anymore

**Comment by olegstepura** [comment]
Well, if it help - sure
