### ISSUE TITLE
Branch 2.0 with composer and on packagist.org

### ISSUE THREAD

**Issue by thomas2411** [FriendsOfSymfony/FOSFacebookBundle#138]
Hi,

is there a chance to add Branch 2.0 to http://packagist.org/packages/friendsofsymfony/facebook-bundle ?

**Comment by lsmith77** [comment]
there is no need. both the 0.6.0 and master are compatible with 2.0 and 2.1

**Comment by stof** [comment]
Btw, there is no 2.0 branch at all in the bundle, so why asking to add in on packagist ?

**Comment by thomas2411** [comment]
Aha, it was merged to master? I didn't notice, sorry
