### ISSUE TITLE
Fatal error: Call to undefined method

### ISSUE THREAD

**Issue by sela** [FriendsOfSymfony/FOSFacebookBundle#141]
I followed the instructions in the READme file and try with symfony 2.0.13 and I can find why I keep getting this error
Fatal error: Call to undefined method Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension::addSecurityListenerFactory() in /Applications/MAMP/htdocs/Symfony/vendor/bundles/FOS/FacebookBundle/FOSFacebookBundle.php on line 25

**Comment by lsmith77** [comment]
are you using the correct branch of this Bundle? aka not master

**Comment by sela** [comment]
not sure actually. I noticed there are 4 branches. master, 2.0 and 2 more. where can i find which one is compatible with symfony 2.0?

**Comment by lsmith77** [comment]
its 2.0 .. as stated in the docs ..

**Comment by sela** [comment]
when I check the README in deps the cofig is 
version=origin/master
which i believe is master and not 2.0?

With 2.0 I get the following error
InvalidConfigurationException: The child node "providers" at path "security" must be configured.
working on my config files now to see why it happens
