### ISSUE TITLE
RedirectResponse in a Facebook Context (merge with FacebookCanvasAppBundle)

### ISSUE THREAD

**Issue by dator-zz** [FriendsOfSymfony/FOSFacebookBundle#16]
Hi,

I think we need to add a new RedirectResponse for this bundle.
Facebook does not take care of http redirect, we need to redirect with javascript if we are in a Facebook context (ie Facebook Apps)

Here is the code :

https://gist.github.com/863839

What do you think ? :)

**Comment by lsmith77** [comment]
could you convert this into a PR? makes reviewing easier.

**Comment by dator-zz** [comment]
According to my latest research and tests, this bundle is awesome for using facebook connect, but not for developing facebook apps.
- The RedirectResponse must be handle in js or <fb:redirect url=""/>, not with meta.
- The Routing must get rid of (index|app)_dev.php . if you keep it, you will have 500 errors.
- The Route Url must begin with the app_name (or canvas_name) like apps.facebook.com/appName
- If you want to have routes in your facebook apps (like apps.facebook.com/appName/users/edit/1 you need to add a target="_top" to all your url

it's quit a lot of changes for this bundle to handle facebook apps development no?

**Comment by lsmith77** [comment]
i have no experience with facebook apps, so if you could look into working on the necessary changes it would be great.

**Comment by lsmith77** [comment]
I am still hoping that someone writes a PR to merge https://github.com/caefer/FacebookCanvasAppBundle

cc @caefer

**Comment by caefer** [comment]
I'm willing to help (once back from holidays) but I don't see myself doing it alone as I still think the security stuff is far too complicated to mess around with. Someone drop me a line and we can arrange something.

**Comment by dustinwhittle** [comment]
+1 for integrating FacebookCanvasAppBundle -- let me know if you need/want help.

**Comment by lsmith77** [comment]
@dustinwhittle: that would be awesome. i must admit right now i have no work needs for this bundle and i dont really enjoy working with the Facebook api to make it my spare time priority :)

**Comment by dustinwhittle** [comment]
I have some projects that will require canvas support, so I will refactor the bundle as I have time over the next few weeks. @caefer are you fine with merging all functionality into FacebookBundle?

**Comment by caefer** [comment]
@dustinwhittle totally cool with it! But on holidays right now and not
back before mid-June. From then on you can count me in though I
switched to javascript only canvas apps personally by now.

2011/5/26, dustinwhittle
reply@reply.github.com:

> I have some projects that will require canvas support, so I will refactor
> the bundle as I have time over the next few weeks. @caefer are you fine with
> merging all functionality into FacebookBundle?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/FriendsOfSymfony/FacebookBundle/issues/16#comment_1240618

## 

Gesendet von meinem Mobilgerät

your daily symfony blog:
test.ical.ly http://goog_1096806570 | grabbing PHP by its
ballshttp://test.ical.ly

**Comment by diegoholiveira** [comment]
@caefer and @dustinwhittle i can help to merge this two bundles, i'm in a project that use a lot of resources from facebook and a i believe that this merging will be awesome to my project, so, just let me know about the planning to merge this two bundles.
:)

**Comment by caefer** [comment]
hi all,

I am back from holidays and can spend a few hours per week on this. but as the motivation to create this bundle was my lack of understanding of the FOS bundle I can not picture myself as leading this migration. I will be able to answer for my bundle and to perform certain jobs but I'm not able to tell what needs to be done. So who can?

**Comment by ahilles107** [comment]
al we need is a hack in - EntryPoint 

``` php
        $response = new RedirectResponse($loginUrl = $this->facebook->getLoginUrl(
           array(
                'display' => $this->options->get('display', 'page'),
                'scope' => implode(',', $this->permissions),
                'redirect_uri' => str_replace('http://example.com/facebook/', 'http://apps.facebook.com/xxx/', $request->getUriForPath($this->options->get('check_path', ''))),
            ))

        );
        echo '<script>top.location.href="'.$loginUrl.'"</script>';
        die;
```

help me with added access to 2 another config elements  and i will do PR. (this patch will be work with canvas and page tab application)

**Comment by lsmith77** [comment]
would be great if one of you could test https://github.com/FriendsOfSymfony/FOSFacebookBundle/pull/52

**Comment by lsmith77** [comment]
#52 has been merged. please reopen if not yet solved.
