### ISSUE TITLE
FOSUser + FOSFacebook integration

### ISSUE THREAD

**Issue by tiagojsag** [FriendsOfSymfony/FOSFacebookBundle#181]
Hi,

I'm trying to integrate both bundles on my project, using symfony 2.1 RC1, and I'm having a hard time getting FB auth working :/
Can someone provide a link to a more or less recent working example? I've looked around, but all I could find were old examples (some of them use symfony 2.0.0).

Also, it would be nice of the documentation could be updated with a working example of FosUser+ FosFB, as right now it's quite confusing

cheers

**Comment by tiagojsag** [comment]
https://github.com/djepo/TemplateViergeSymfony2

**Comment by Raulken** [comment]
when i install the vendor....return error.......

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package twig/twig == 1.9.9999999.9999999-dev could not be found.
  Problem 2
    - Installation request for sensio/generator-bundle == 2.1.9999999.9999999-dev -> satisfiable by sensio/generator-bundle 2.1.x-dev.
    - Can only install one of: sensio/generator-bundle dev-master, sensio/generator-bundle 2.1.x-dev.
    - Installation request for sensio/generator-bundle == 9999999-dev -> satisfiable by sensio/generator-bundle dev-master.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
