### ISSUE TITLE
Unrecognized options "factories" under "security"

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSFacebookBundle#195]
"In Symfony 2.1 the custom factories for the firewall configuration are now registered during the build method of bundles instead of being registered by the end-user. 
This means that you will need to remove the 'factories' keys in your security configuration."

So where and how do i register the factory "%kernel.root_dir%/../src/FOS/FacebookBundle/Resources/config/security.xml" with the new FOSFacebookBundle?

A quick hint would be appreciated :)

Kind regards

**Comment by stof** [comment]
@fabianbartsch The doc tells you to **remove** this setting. In Symfony 2.1, the end user does not need to register all new factories by hand. Each bundle can register the factories it provides

**Comment by ghost** [comment]
Thanks for your answer!
