### ISSUE TITLE
FacebookProvider hide all kind of exceptions

### ISSUE THREAD

**Issue by wujashek** [FriendsOfSymfony/FOSFacebookBundle#21]
In authenticate method even PDOExceptions are catched and never displayed or logged.
This hurts debugging a lot.

**Comment by stof** [comment]
I think catching PDOException is also done by the core provider as they could contain some critical datas

**Comment by lsmith77** [comment]
yeah .. the only thing we can think about is logging them manually to the profiler.

**Comment by stof** [comment]
yeah, this is done in the security listeners using the debug level. I can probably be done in the bundle too.

**Comment by lsmith77** [comment]
@wujashek: would you be motivated to work on that?

**Comment by wujashek** [comment]
@lsmith77: it is all over symfony security component for example RememberMe has catch(\Exception $e), so you ends with xdebug as your best friend.

**Comment by lsmith77** [comment]
Yes, this is intentional by the SecurityBundle since you don't want to leak just any Exception. We have to get even tighter there or rather we must find a way to flag which Exceptions are supposed to be "leaked" to the end user and which not:
http://trac.symfony-project.org/ticket/9523

Now the Exception cause should however be logged to the debug toolbar.

**Comment by wujashek** [comment]
We need another ticket for showing exception to developers, without it newcomers will by irriitated, how many of theme uses xdebug ?

**Comment by lsmith77** [comment]
But this is not an issue for this bundle, this is a topic for SecurityBundle itself.

**Comment by wujashek** [comment]
Yes, but maybe a short notice in documentation will help newcomers ?

**Comment by lsmith77** [comment]
I think the notice would be better placed in the Security documentation.

**Comment by lsmith77** [comment]
@wujashek: did you submit a notice for the official security documentation? btw those docs recently got tweaked. anyway closing the issue here ..
