### ISSUE TITLE
Change to Logout Handler requires change to ReadMe

### ISSUE THREAD

**Issue by timbostop** [FriendsOfSymfony/FOSFacebookBundle#221]
Recent checkout https://github.com/FriendsOfSymfony/FOSFacebookBundle/commit/1b257670ca39240708c086cc98c550373e500ff1 (1b257670ca39240708c086cc98c550373e500ff1) breaks things because the configuration specified in the README.md expects to have the service "fos_facebook.logout_handler" which no longer exists...

This causes an error like:
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  The service "security.firewall.map.context.main" has a dependency on a non-existent service "fos_facebook.logout_handler".  

when updating composer.

README.md needs these lines removing:

logout:
                  handlers: ["fos_facebook.logout_handler"]

**Comment by diegoholiveira** [comment]
Done. thanks for pointing that.
