### ISSUE TITLE
Include facebook friends into website

### ISSUE THREAD

**Issue by lukeman83** [FriendsOfSymfony/FOSFacebookBundle#245]
Hi,
how can I include facebook friends into website?

**Comment by dupuchba** [comment]
@lukeman83 do you mean inviting friends of your user? Do you have any examples/resources?

**Comment by lukeman83** [comment]
I mean invite friends getting friend list by facebookid or by credentials and sending notification to user facebook friends!

**Comment by dupuchba** [comment]
Ok so you have to check what facebook call "Request Dialog" [here](https://developers.facebook.com/docs/reference/dialogs/requests/)

But they give only example in javascript which should be fine. If you want to use php, you can still read this blog post on facebook [developer](https://developers.facebook.com/blog/post/464/).

**Comment by stof** [comment]
Closing this as the bundle is about authenticating through Facebook. To do other API calls, you should use their SDK.
