### ISSUE TITLE
"The Facebook user could not be retrieved from the session." only on server side

### ISSUE THREAD

**Issue by pierregoutheraud** [FriendsOfSymfony/FOSFacebookBundle#248]
Hi,

I am using Symfony v2.0.9, FOSUserBundle and FOSFacebookBundle. Facebook login and signup works well in local but I get this errror while trying on online server : 
"The Facebook user could not be retrieved from the session."

I looked for that line of code which is in FacebookProvider.php : my fbsr_ cookie is set correctly but $this->facebook->getUser() is not returning anything...

What could be the issue ?
(I already added the JS delay before redirecting to "_security_check_facebook")

Thanks,
Pierre.

**Comment by fnash** [comment]
Whats was the problem please?
