### ISSUE TITLE
Scrutinizer

### ISSUE THREAD

**Issue by diegoholiveira** [FriendsOfSymfony/FOSFacebookBundle#249]
I just add a config file for scrutinizer on the repository, who is admin of this repo to add it on scrutinizer?

**Comment by diegoholiveira** [comment]
ping @stof

**Comment by stof** [comment]
@diegoholiveira all the FOS members are owners of the organizations (or should at least)

**Comment by diegoholiveira** [comment]
I try do add it but it say that i'm not a admin of FOSFacebookBundle :(

**Comment by stof** [comment]
OK, so 15 FOS members are owners over 21. I guess the newest members have not been awarded the ownership.

I gave the admin rights on the FOSFacebookBundle repo.

I also enabled scrutinizer with the same global build config than used for FOSUB. you should remove your file from the repo (which is not valid Yaml btw) to make it use the global one.
Can you go in the scrutinizer panel to see if you can access the FOSFacebookBundle repo when it has been enabled by me and see its global config ? I'm curious to know how organizations are supported on scrutinizer

**Comment by stof** [comment]
ah, I found the page to add other admins for scrutinizer so I guess it has to be done manually

**Comment by diegoholiveira** [comment]
Nice.

I removed .scrutinizer.yml from this repo.

Can you add me at scrutinizer-ci.com? my github account is linked there.

**Comment by stof** [comment]
already done :)
