### ISSUE TITLE
setFacebookId() should not overwrite salt

### ISSUE THREAD

**Issue by drgomesp** [FriendsOfSymfony/FOSFacebookBundle#254]
On the documentation regarding the FOSUserBundle integration, the custom provider has a method called `setFacebookId()`, like this:

``` php
    public function setFacebookId($facebookId)
    {
        $this->facebookId = $facebookId;
        $this->setUsername($facebookId);
        $this->salt = '';
    }
```

But in order for the integration to work properly, this method cannot overwrite the salt, otherwise the user will never be able to login using the username and password combination again.

The correct way is this:

``` php
    public function setFacebookId($facebookId)
    {
        $this->facebookId = $facebookId;
        $this->setUsername($facebookId);
    }
```

Should we update the docs or just add this custom provider to the bundle?

**Comment by diegoholiveira** [comment]
IMo, we should update the docs only. I don't think that we should include custom providers on this bundle.

**Comment by diegoholiveira** [comment]
Can you submit a PR with the right documentation?
