### ISSUE TITLE
Symfony 2.3 Version

### ISSUE THREAD

**Issue by andreasschmidt** [FriendsOfSymfony/FOSFacebookBundle#258]
The bundle should really consider being usable with the symfony 2.3 version :) Do you see any problems, simply updating the composer.json file?

**Comment by diegoholiveira** [comment]
I guess you will not have problems with sf2.3. Try it and report any problems that you found.

**Comment by abenbachir** [comment]
any estimation date  ?

**Comment by fabysdev** [comment]
it's not possible to install the bundle with symfony 2.3:

```
-friendsofsymfony/facebook-bundle 1.1.x-dev requires symfony/security >=2.1,<2.3 -> satisfiable by symfony/symfony[2.1.x-dev, 2.2.x-dev, v2.1.0, v2.1.1, v2.1.10, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.0-BETA1, v2.2.0-BETA2, v2.2.0-RC1, v2.2.0-RC2, v2.2.0-RC3, v2.2.1], symfony/security[2.1.x-dev, 2.2.x-dev, v2.1.0, v2.1.1, v2.1.10, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.0-BETA1, v2.2.0-BETA2, v2.2.0-RC1, v2.2.0-RC2, v2.2.0-RC3, v2.2.1].
```

Maybe change it to ">=2.1" ?

**Comment by abenbachir** [comment]
I downgraded my symfony verison to 2.2.x, there are others bundles who did not support the symfony2.3 yet.

**Comment by Spone** [comment]
Can you bump the Symfony required version so we can install the FacebookBundle with Composer?

**Comment by willdurand** [comment]
Yup, I think it's just a matter of composer constraint. Your best bet would be to submit a PR :)

**Comment by vinzzouze** [comment]
Hi,
I have a problem with Sf 2.3 in FOSFacebookBundle / Facebook / FacebookSessionPersistence.php,
line 36.
It use Request::isProxyTrusted(); that it does not exist anymore.

**Comment by diegoholiveira** [comment]
I just tag the 1.2 version that is already working on sf2.3 :)
