### ISSUE TITLE
FacebookProvider::loadUserByUsername never gets called

### ISSUE THREAD

**Issue by stoefln** [FriendsOfSymfony/FOSFacebookBundle#27]
Hi there!

I have inserted some heavy debug code, to figure out whether the method gets called (since no DB record is created after login)

<pre>
public function loadUserByUsername($username)
    {
        print_r("loadUserByUsername called!");
        die();
...
</pre>

The debug code is never executed.
The provider service is configured, and the class is in the right place.
Any hints?

BR Stephan

**Comment by stoefln** [comment]
got that sorted out today. at this point i'm still so confused that i can't give any hints on the topic.
thanks to helmer for guiding me!

**Comment by marbemac** [comment]
I'm having this issue after upgrading the new SDK3 code. loadUserByUsername in my custom provider never get's called. When I try to login I simply get taken back to the login form again (facebook login button). I have double checked everything and I made all the required changes when moving to SDK3 (using basefacebook etc).

**Comment by stoefln** [comment]
yeah, me too. again!

**Comment by stoefln** [comment]
I'm still far away from looking through, but this line validates to false:
https://github.com/facebook/php-sdk/blob/master/src/base_facebook.php#L436

the reason is that $this->getAccessToken() == $this->getApplicationAccessToken()

so there is no user returned in 
https://github.com/FriendsOfSymfony/FOSFacebookBundle/blob/master/Security/Authentication/Provider/FacebookProvider.php#L50

the consequence is, that 
$user = $this->userProvider->loadUserByUsername($uid);

never gets called...

can someone who has a better understanding of oauth help here?

**Comment by marbemac** [comment]
Yeah, any luck on this?

**Comment by Taichou** [comment]
Hi,
I have the same problem :s.

**Comment by marbemac** [comment]
Hmm, do any of the bundle core contributors have ideas on this?

**Comment by lsmith77** [comment]
i am really sorry .. but i just have my hands full with work and the CMF stuff. i remember @caefer and @dustinwhittle wanted to start contributing to this package .. not sure if they are still interested ..

**Comment by caefer** [comment]
unfortunately not so much a matter of interest as of time available..

**Comment by ahilles107** [comment]
https://github.com/FriendsOfSymfony/FOSFacebookBundle/pull/55 - This commit solves the problem

**Comment by lsmith77** [comment]
please test again, reopen if necessary
