### ISSUE TITLE
P3P

### ISSUE THREAD

**Issue by antoine-tissier** [FriendsOfSymfony/FOSFacebookBundle#28]
Hi,

I am just reading the source code of the bundle for testing purpose.

I am wondering if the P3P headers should not been inserted ?

http://www.romualb.com/2011/03/15/222/p3p_platform_for_privacy_preferences_gestion_des_sessions_php_de_sites_tiers_avec_ie.html

Thanks in advance 

Regards

Antoine Tissier

**Comment by dustinwhittle** [comment]
Any p3p tag should not be set by a bundle as it is specific to each sites privacy policies. Should this be closed?

**Comment by schmittjoh** [comment]
Closing this as dustin said, you should make these global settings yourself.
