### ISSUE TITLE
Method not allowed: POST

### ISSUE THREAD

**Issue by dnizetic** [FriendsOfSymfony/FOSFacebookBundle#283]
At point 4) in documentation (part 1) this is the required route:
# application/config/routing.yml

_security_check:
  pattern:  /login_check

After logging in with facebook, I get redirected to /login_check:

```
function goLogIn(){
    window.location.href = "{{ path('_security_check') }}";
}
```

But, FOSUSER already occupies /login_check and I get an error:

No route found for "GET /login_check": Method Not Allowed (Allow: POST)

Can anyone explain this?

**Comment by willdurand** [comment]
Why did you close this issue?
