### ISSUE TITLE
add support for v3 php sdk

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSFacebookBundle#29]

**Comment by dustinwhittle** [comment]
I am up to work on this, but I am waiting until the support for javascript sdk. Otherwise they are not compatible as cookie signature has changed.

**Comment by dustinwhittle** [comment]
FYI - In order for the current releases to work you should use facebook-php-sdk tag v2.1.2 (not master which is 3.x)

**Comment by stoefln** [comment]
Anyone knows when this will happen? An aproximation would be useful...

**Comment by dustinwhittle** [comment]
The facebook blog post said javascript sdk compatibility was four week away - https://developers.facebook.com/blog/post/503

**Comment by shakir33** [comment]
hello,
when i updated to the version 3 of facebook sdk i receive this error :
ErrorException: Notice: A session had already been started - ignoring session_start() in \vendor\symfony\src\Symfony\Component\HttpFoundation\SessionStorage\NativeSessionStorage.php line 81

any idea ?

**Comment by diegoholiveira** [comment]
@shakir33: it's because the php-sdk3 have a session_start in their constructor. This cause conflict with the framework, that have their own way to deal with sessions.

**Comment by stof** [comment]
@shakir33 This bundle is not updated to work with the v3 yet. It is in the TODO list. And it will probably wait the release of the new JS api too as the bundle uses both the PHP and the JS api.

**Comment by schmittjoh** [comment]
I've upgraded the code to use the Facebook SDK 3. Closing this.
