### ISSUE TITLE
Missing parameter fos_facebook.channel.expire - error 500

### ISSUE THREAD

**Issue by dkorsak** [FriendsOfSymfony/FOSFacebookBundle#293]
The parameter "fos_facebook.channel.expire" must be defined. 
For URL /channel.html

**Comment by dkorsak** [comment]
Any progress?

**Comment by diegoholiveira** [comment]
If you take at look on the Configuration class, you will see that there is a default value for the fos_facebook.channel.expire: https://github.com/FriendsOfSymfony/FOSFacebookBundle/blob/master/DependencyInjection/Configuration.php#L58

Try to use the master branch. If the problem persist, can you provide some unit tests that expose the bug?

thanks a lot
