### ISSUE TITLE
Impossible to update with symfony 2.4

### ISSUE THREAD

**Issue by djepo** [FriendsOfSymfony/FOSFacebookBundle#296]
The problem is with symfony/security wich requires version >=2.2,<2.4

**Comment by PapyDanone** [comment]
same here

**Comment by stof** [comment]
I strongly suggest you to switch to HWIOAuthBundle instead of using FOSFacebookBundle. It has a better implementation and is actively maintained. Anyway, the dev version of the bundle now allows 2.4

**Comment by djepo** [comment]
Thanks. I will change to that bundle when i'll have enough time ^^
