### ISSUE TITLE
Allow Symfony 2.4

### ISSUE THREAD

**Issue by xavierrobin** [FriendsOfSymfony/FOSFacebookBundle#297]
Impossible to use with composer on symfony 2.4

**Comment by 1337er** [comment]
- friendsofsymfony/facebook-bundle 1.2.1 requires symfony/security >=2.2,<2.4 -> satisfiable by symfony/symfony[v2.2.0, v2.2.1, v2.2.10,...]
  Same here!

**Comment by Sybio** [comment]
+1

**Comment by stof** [comment]
use the dev version of the bundle

**Comment by diegoholiveira** [comment]
I'll tag a stable version for sf2.4 later.

**Comment by diegoholiveira** [comment]
1.3 stable is compatible with sf 2.4.
