### ISSUE TITLE
Problem with changing logged users

### ISSUE THREAD

**Issue by antonioperic** [FriendsOfSymfony/FOSFacebookBundle#299]
Hi,
I am working on one facebook app. Use case is simple: user need to give some information and after that he can upload photo and other people are voting for best photo. Simple photo contest.

I tried to do this with FOSFacebook and everything is ok except two things:
- app is facebook canvas app and every time after authentication it redirects me to my server (doesn't stay in facebook chrome)
- second thing is that if I logged out and login with other facebook user in facebook, the first user is still logged in my application. How can I retrieve user which is currently logged in facebook or if isn't to ask him to log in.

**Comment by michaelslon** [comment]
i noticed you closed the issue. i'm having a similar problem as well. if you found a work around could you please share?
