### ISSUE TITLE
[Question] Different user types

### ISSUE THREAD

**Issue by Sydney-o9** [FriendsOfSymfony/FOSFacebookBundle#301]
I am using a discrimination table for my users:
- Buyers  ( /Acme//Entity/Buyer extends Acme//Entity/User )
- Sellers  ( /Acme//Entity/Seller extends Acme//Entity/User )

Therefore a user is either a Buyer or a Seller.

Is it possible in that case to use FOSFacebookBundle and ask what type of users they would like to be?

**Comment by diegoholiveira** [comment]
Since you profiles has the same base (Acme/Entity/User), what you need to do is use this base as entity that will be used.

**Comment by Sydney-o9** [comment]
Thanks @diegoholiveira, but this won't let the user choose whether he wants to be a buyer or seller :( 

I am just trying to think of a way to do that. Is it possible to ask the user on first login, what he wants to be?

Your insight on this would be very hepful @diegoholiveira 

Thanks so much!
