### ISSUE TITLE
Bundle compatibility with Symfony 2.4

### ISSUE THREAD

**Issue by alexbaciu** [FriendsOfSymfony/FOSFacebookBundle#304]
Hello,

Is it possible to have this bundle working with Symfony 2.4 version?
Here is the error message that I've received when I am trying to install the bundle via composer:

"
Problem 1
    - Installation request for symfony/framework-standard-edition 2.4.x-dev -> satisfiable by symfony/framework-standard-edition[2.4.x-dev].
    - Conclusion: remove symfony/symfony v2.4.1
    - symfony/framework-standard-edition 2.4.x-dev requires friendsofsymfony/facebook-bundle 1.2.\* -> satisfiable by friendsofsymfony/facebook-bundle[1.2.0, 1.2.1].
    - friendsofsymfony/facebook-bundle 1.2.0 requires symfony/security >=2.2,<2.4 -> satisfiable by symfony/symfony[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.2, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9], symfony/security[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.2, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9].
    - friendsofsymfony/facebook-bundle 1.2.1 requires symfony/security >=2.2,<2.4 -> satisfiable by symfony/symfony[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.2, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9], symfony/security[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.2, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9].
    - Can only install one of: symfony/symfony[v2.4.1, v2.3.0].
    - Can only install one of: symfony/symfony[v2.4.1, v2.3.1].
    - Can only install one of: symfony/symfony[v2.4.1, v2.3.2].
    - Can only install one of: symfony/symfony[v2.4.1, v2.3.3].
    - Can only install one of: symfony/symfony[v2.4.1, v2.3.4].
    - Can only install one of: symfony/symfony[v2.4.1, v2.3.5].
    - Can only install one of: symfony/symfony[v2.4.1, v2.3.6].
    - Can only install one of: symfony/symfony[v2.4.1, v2.3.7].
    - Can only install one of: symfony/symfony[v2.4.1, v2.3.8].
    - Can only install one of: symfony/symfony[v2.4.1, v2.3.9].
    - Can only install one of: symfony/symfony[v2.4.1, v2.2.0].
    - Can only install one of: symfony/symfony[v2.4.1, v2.2.1].
    - Can only install one of: symfony/symfony[v2.4.1, v2.2.10].
    - Can only install one of: symfony/symfony[v2.4.1, v2.2.11].
    - Can only install one of: symfony/symfony[v2.4.1, v2.2.2].
    - Can only install one of: symfony/symfony[v2.4.1, v2.2.3].
    - Can only install one of: symfony/symfony[v2.4.1, v2.2.4].
    - Can only install one of: symfony/symfony[v2.4.1, v2.2.5].
    - Can only install one of: symfony/symfony[v2.4.1, v2.2.6].
    - Can only install one of: symfony/symfony[v2.4.1, v2.2.7].
    - Can only install one of: symfony/symfony[v2.4.1, v2.2.8].
    - Can only install one of: symfony/symfony[v2.4.1, v2.2.9].
    - don't install symfony/security v2.2.0|don't install symfony/symfony v2.4.1
    - don't install symfony/security v2.2.1|don't install symfony/symfony v2.4.1
    - don't install symfony/security v2.2.10|don't install symfony/symfony v2.4.1"

**Comment by diegoholiveira** [comment]
What FOSFacebookBundle are you using?

**Comment by stof** [comment]
The issue is that you specifically ask for FOSFacebookBundle `1.2.*`, and so you forbid composer to choose the 1.3.0 release, which is the one you need
