### ISSUE TITLE
Recommended version of FOSFacebookBundle to install?

### ISSUE THREAD

**Issue by mappedinn** [FriendsOfSymfony/FOSFacebookBundle#319]
Hi,

I am wondering what is recommended version of FOSFacebookBundle to install.

**Notice:** I am using Symfony 2.3.12

Thanks

**Comment by mappedinn** [comment]
No proposal?

**Comment by soulghard** [comment]
The last one is just fine :) 

"friendsofsymfony/facebook-bundle": "dev-master"

**Comment by stof** [comment]
My answer would be "none". Using HWIOAuthBundle to handle the oauth2 implementation is much better:
- the implementation is much better (it was done later than the FacebookBundle, so we all knew the security system better)
- it does not rely on the Facebook SDK for the OAuth handling, which is a pain to integrate into other apps (it was not designed to be integrated with frameworks)
- it is better maintained (none of the FOS guys is actually using FOSFacebookBundle AFAIK)

**Comment by mappedinn** [comment]
Thank you @stof for your answer.

Actually, FOSFacebookBundle is installed in my website and working perfectly!

I will consider to install HWIOAuthBundle .

Thank you for you advice!
