### ISSUE TITLE
Call to undefined method Facebook::getSession()

### ISSUE THREAD

**Issue by acki** [FriendsOfSymfony/FOSFacebookBundle#32]
Hi there

If i initialize the thing in my Twig template with {{ facebook_initialize({'xfbml': true}) }}, i get this error:
Fatal error: Call to undefined method Facebook::getSession() in /my/project/home/vendor/bundles/FOS/FacebookBundle/Templating/Helper/FacebookHelper.php on line 47

Can you help me? What's going wrong here?

Implemented the thing in a +- empty symfony 2 beta 3 project, with your README provided in your github package.

Thanks a lot

Chris

**Comment by stof** [comment]
Are you using the sdk v2 or v3 ? the bundle currently requires the v2.

**Comment by acki** [comment]
Yeah, my fault, this was the point.
Was a little bit too tired last night ;)

Can you say me how to fix the tag in the .gitmodules?

**Comment by stof** [comment]
You go in your facebook submodule, you checkout the v2.1.2 tag and you commit the change in the main repo.

**Comment by acki** [comment]
Thanks a lot!

**Comment by gigo6000** [comment]
It would be nice if you put this in the README thanks
