### ISSUE TITLE
$_SERVER - missing arr keys when using CLI

### ISSUE THREAD

**Issue by richsage** [FriendsOfSymfony/FOSFacebookBundle#34]
So, I'm not sure if this is an issue with the FacebookBundle or not... :-)  The Facebook API checks for the `HTTP_HOST` and `REQUEST_URI` keys in the `$_SERVER` array, when the API's `getLoginUrl()` method is called.  These keys aren't present when eg tests are carried out from the command line (I'm using Behat for testing).

Possible solution is presented here: http://stackoverflow.com/questions/5966186/how-to-set-http-host-for-webtestcases-in-symfony2/5975908#5975908

which would need to be done in the `start()` method in the entry point. This feels slightly hacky, but at the moment I can't think of a neater way...

**Comment by lsmith77** [comment]
i dont think there is anything we can sensibly do inside this bundle, so i am closing this ticket. however you might want to open a new issue on symfony itself.

**Comment by richsage** [comment]
Great - thanks :-)
