### ISSUE TITLE
Error in Customer User Provider using the FOS\UserBundle

### ISSUE THREAD

**Issue by gigo6000** [FriendsOfSymfony/FOSFacebookBundle#37]
Hi there,

I think there's an error in the refreshUser method in the FacebookProvider class, I was getting an error telling me that I had no user provider:

There is no user provider for user "Mysite\SiteBundle\Document\User"

But I found out after dumping the User object,  it was that the refreshUser method was trying to get the facebookId  but the User object didn't have one it only had the username at this point (not sure why).  I modified the method to use $user->getUsername() instead of $user->getFacebookId() and is working now.  

Also I noticed that the example User class have getFacebookID() instead of getFacebookId() which is called in this method.

Method from the example FacebookProvider:

```
public function refreshUser(UserInterface $user)
{
    if (!$this->supportsClass(get_class($user)) || !$user->getFacebookId()) {
        throw new UnsupportedUserException(sprintf('Instances of "%s" are not supported.', get_class($user)));
    }

    return $this->loadUserByUsername($user->getFacebookId());
}
```

Modified method:

```
public function refreshUser(UserInterface $user)
{

    if (!$this->supportsClass(get_class($user)) || !$user->getUsername()) {
        throw new UnsupportedUserException(sprintf('Instances of "%s" are not supported.', get_class($user)));
    }

    return $this->loadUserByUsername($user->getUsername());
}
```

Thanks,

Carlos

**Comment by dirkbloessl** [comment]
Had the same issue after updating from beta5.
I had to add the following provider, which made it working again: 
fos_userbundle:
            id: fos_user.user_manager

**Comment by schmittjoh** [comment]
Is this a doc problem, or what's wrong? Can you send a PR to fix it?

**Comment by dirkbloessl** [comment]
You just have to ensure, that FOSUserBundle is configured correctly, after upgrading. In my case it was not, because I didn't set the new mandatory provider. That's not a doc problem, so I don't see a requirement in changing anything ;-)

**Comment by schmittjoh** [comment]
Ok, closing this
