### ISSUE TITLE
upgrading to v3 results in infinite redirects

### ISSUE THREAD

**Issue by richsage** [FriendsOfSymfony/FOSFacebookBundle#44]
Not sure if this is an issue with my code or not, but it worked up until the FOSFacebookBundle was upgraded to use v3 of the SDK.... See https://gist.github.com/1092555 for my security.yml and excerpt from my controller.  Essentially the user clicks a link to eg `www.example.com/signin/facebook` which bounces them to a page requiring the `ROLE_FACEBOOK` role.  This triggers the Facebook authentication and I get the signin page as expected.

However, when I sign in, this now goes back to my app but as the authentication in Symfony2 hasn't taken place yet, the user is then bounced back to Facebook and subsequently back to my app etc, resulting in an infinite redirect.  This wasn't happening with v2.1.2 of the Facebook SDK, and I've updated both the FOSFacebookBundle and Facebook SDK accordingly.

Is there a step missing from the install docs which is relevant to v3? I've applied the config as per the installation, but still no dice.

**Comment by ahilles107** [comment]
https://github.com/FriendsOfSymfony/FOSFacebookBundle/pull/55 - This commit solves the problem.

**Comment by lsmith77** [comment]
please test again, reopen if necessary

**Comment by richsage** [comment]
works perfectly, thanks both :-)
