### ISSUE TITLE
FOSFacebookBundle is incompatible with php-sdk 3.0.1

### ISSUE THREAD

**Issue by ahilles107** [FriendsOfSymfony/FOSFacebookBundle#49]
is a new way to store and use the facebook csrf token

commit - https://github.com/facebook/php-sdk/commit/ab2d46df947d113d7c20fc46d8865a66168fcf05

**Comment by stoefln** [comment]
Can you tell us what the consequences look like? This might be related to the other bugs...

**Comment by ahilles107** [comment]
i have exception from facebook class and "CSRF state token does not match one provided." in logs.

**Comment by fran6co** [comment]
Could you check if this patch https://github.com/FriendsOfSymfony/FOSFacebookBundle/pull/53 fixes your problem? It did for me.

**Comment by marbemac** [comment]
Hey so I tried with the patch and no luck. Thanks for trying though. I'm trying to track down the bug this week, but I don't quite understand how the bundle works yet.

**Comment by ahilles107** [comment]
https://github.com/FriendsOfSymfony/FOSFacebookBundle/pull/55 - This commit solves the problem
