### ISSUE TITLE
Permission request only for basic information

### ISSUE THREAD

**Issue by gigo6000** [FriendsOfSymfony/FOSFacebookBundle#60]
Hi,

When clicking the login button it is only asking permission to access basic user info ignoring all the other permissions, this was working before so I'm not sure if this is a problem with javascript SDK.

This is code of my button:

```
   <fb:login-button scope="email,user_birthday,user_location,offline_access,user_checkins,friends_checkins" autologoutlink="1"></fb:login-button>
```

**Comment by ahilles107** [comment]
Facebook is insane ;/ they forget change perms to scope in login-button. PR fix incoming

**Comment by ahilles107** [comment]
more info http://developers.facebook.com/docs/reference/plugins/login/

**Comment by gigo6000** [comment]
I guess all the sites using the login button and Oauth are having this issue, I can't believe they didn't notice this

**Comment by ahilles107** [comment]
i just send a PR https://github.com/FriendsOfSymfony/FOSFacebookBundle/pull/61/files

**Comment by gigo6000** [comment]
I think perms doesn't work either :(

**Comment by ahilles107** [comment]
gigo6000 - for me work's.

**Comment by gigo6000** [comment]
do you use oauth: true ?

**Comment by ahilles107** [comment]
yes, but i delete cookie before.

**Comment by gigo6000** [comment]
then I'm not sure why I get :

OAuth2 specification states that 'perms' should now be called 'scope'. Please update.
[Break On This Error] FB.provide('',{getLoginStatus:function...signed_request,code'});return a;}}});

**Comment by ahilles107** [comment]
ehh.... i don't know. According http://developers.facebook.com/docs/reference/plugins/login/ we must set perms, but error message is clear. Maybe wy shoud revert last "fix" ?? @lsmith?

**Comment by lsmith77** [comment]
yeah .. i just revert that fix

**Comment by gigo6000** [comment]
I think the best option for now is to go back to the php SDK 2.1.1 branch and remove the outh option, what do you guys think ?

**Comment by gigo6000** [comment]
The bug is reported here but there is no fix in almost a month : http://bugs.developers.facebook.net/show_bug.cgi?id=19733

**Comment by ahilles107** [comment]
@gigo6000 - we have problem (Facebook have problem) only with login-button, right? OAuth 2.0 migration - October 1, 2011    - All apps must migrate to OAuth 2.0 and expect an encrypted access token. We can not go back.

**Comment by gigo6000** [comment]
It was finally fixed: http://bugs.developers.facebook.net/show_bug.cgi?id=19733

**Comment by logiclabz** [comment]
Facebook login connect has migrated to oauth2.0 creating Facebook Login Error as Oauth2 specification states that 'perms' should now be called 'scope'
http://blog.logiclabz.com/javascript/facebook-login-error-oauth2-specification-states-that-perms-should-now-be-called-scope.aspx
