### ISSUE TITLE
InvalidConfigurationException OR Service Not Found Exception

### ISSUE THREAD

**Issue by ohFRY** [FriendsOfSymfony/FOSFacebookBundle#69]
Hi ! I'm brand new here... I've done everything it is written to set up the FOSFacebookBundle.

but when cleaning the cache, I receive this:

---

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException] Invalid configuration for path "security.firewalls.public": The check_path "^/login_check$" for login method "fos_facebook" is not matched by the firewall pattern "^/.*".

  [LogicException]
  The check_path "^/login_check$" for login method "fos_facebook" is not matched by the firewall pattern "^/.*".

---

So I put a # before security.firewalls.public pattern "^/.\* in the security.yml

But I got this when cleaning the cache:

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]   The service "my.facebook.user" has a dependency on a non-existent service "fos_user.user_manager".

And I got this when trying to access to any page:

---

Whoops, looks like something went wrong.

1/1 ServiceNotFoundException: The service "my.facebook.user" has a dependency on a non-existent service "fos_user.user_manager".
in PATH\OF\MY\PROJECT\vendor\symfony\src\Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass.php line 59
at CheckExceptionOnInvalidReferenceBehaviorPass->processReferences() in PATH\OF\MY\PROJECT\vendor\symfony\src\Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass.php line 43
at CheckExceptionOnInvalidReferenceBehaviorPass->processDefinition() in PATH\OF\MY\PROJECT\vendor\symfony\src\Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass.php line 37
at CheckExceptionOnInvalidReferenceBehaviorPass->process() in PATH\OF\MY\PROJECT\vendor\symfony\src\Symfony\Component\DependencyInjection\Compiler\Compiler.php line 119
at Compiler->compile() in PATH\OF\MY\PROJECT\vendor\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php line 436
at ContainerBuilder->compile() in PATH\OF\MY\PROJECT\app\bootstrap.php.cache line 868
at Kernel->buildContainer() in PATH\OF\MY\PROJECT\app\bootstrap.php.cache line 779
at Kernel->initializeContainer() in PATH\OF\MY\PROJECT\app\bootstrap.php.cache line 513
at Kernel->boot() in PATH\OF\MY\PROJECT\app\bootstrap.php.cache line 544
at Kernel->handle() in PATH\OF\MY\PROJECT\web\app_dev.php line 20

---

**Comment by stof** [comment]
`fos_user.user_manager` is a service of FOSUserBundle. It seems like you copied the example about integrating FOSFacebookBundle with FOSUserBundle without having FOSUserBundle in your project.

**Comment by ohFRY** [comment]
thanks a lot for your comment here and there : http://bit.ly/qHg32O
I do have copied the example to see how it works. It was the only example I've found online.

And I do have install FOSuserBundle. It is weird that is doesn't seem installed 
This is the end of my _deps_ file
I've executed **./bin/vendors install** instead of **update** as you said in the link above. But, I have the same output I have written in the first comment here.

> [FOSFacebookBundle]
>    git=git://github.com/FriendsOfSymfony/FOSFacebookBundle.git
>    target=/bundles/FOS/FacebookBundle
> 
> [FOSUserBundle]
>     git=https://github.com/FriendsOfSymfony/FOSUserBundle.git
>     target=/bundles/FOS/UserBundle
> 
> [FacebookSDK]
>    git=https://github.com/facebook/php-sdk.git
>    target=/facebook
> 
> [JMSSecurityExtraBundle]
>   git=https://github.com/schmittjoh/JMSSecurityExtraBundle.git
>   target=/bundles/JMS/SecurityExtraBundle
>   version=origin/1.0.0
> 
> ; Dependencies:
> ;--------------
> [metadata]
>   git=https://github.com/schmittjoh/metadata.git
>   ; version=origin/1.0.x <- make sure to delete this line if it is there
> 
> ; see https://github.com/schmittjoh/JMSAopBundle/blob/master/Resources/doc/index.rst  
> [JMSAopBundle]
>   git=https://github.com/schmittjoh/JMSAopBundle.git
>   target=/bundles/JMS/AopBundle
> 
> [cg-library]
>   git=https://github.com/schmittjoh/cg-library.git
> 
> ; This dependency is optional (you need it if you are using non-service controllers):
> ; see https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/Resources/doc/index.rst
> [JMSDiExtraBundle]
>   git=https://github.com/schmittjoh/JMSDiExtraBundle.git
>   target=/bundles/JMS/DiExtraBundle

**Comment by lsmith77** [comment]
did you also activate the bundle in your AppKernel?

**Comment by ohFRY** [comment]
Oh I forgot to check this. It is true that I have forgotten to add **new FOS\UserBundle\FOSUserBundle(),** to the appKernel (stupid me)

So now... Yes now I did
//appKernel.php

>    public function registerBundles()
>    {
>        $bundles = array(
>            ....
>            new JMS\AopBundle\JMSAopBundle(),
>            new JMS\SecurityExtraBundle\JMSSecurityExtraBundle(),
>            new JMS\DiExtraBundle\JMSDiExtraBundle($this),
>            new Illustra\MainBundle\IllustraMainBundle(),
>            new FOS\FacebookBundle\FOSFacebookBundle(),
>            new FOS\UserBundle\FOSUserBundle(),
>        );

Well it doesn't work because it outputs me this error message when trying to access to any page on the browser

> InvalidConfigurationException: The child node "db_driver" at path "fos_user" must be configured.

But this is not related to the problem I had, it is just about configuration and I will fix it (when I figure how to fix it out)

Thank you @stof & @Ismith77, it was just a stupid missing in the appkernel.php

**Comment by stof** [comment]
Read the doc of FOSUserBundle. There is some mandatory configuration for it.
