### ISSUE TITLE
Namespace has to be the very first statement

### ISSUE THREAD

**Issue by ohFRY** [FriendsOfSymfony/FOSFacebookBundle#70]
Hello everyone,

I still have an issue with integrating this bundle and I'm sorry to bother you with my troubles. 

I've followed the installation section of FOSFacebookBundle and I've done the Optional part to let it work with FOSUserBundle. By the way, FOSUserBundle is installed and configured.

Following the example now I have this error message:
**Fatal error: Namespace declaration statement has to be the very first statement in the script in PathToTheProject\src\MyCorp\MyBundle\Security\User\Provider\FacebookProvider.php on line 3**

of course the first three lines of the file are :

_<?php_

_namespace Illustra\MainBundle\Security\User\Provider;_
_// etc._

I've tried to put this code into the config.yml and I still get this error message (but with the config.yml in the path). I've tried Google the error message, but nothing relevant.

is Anyone having a clue by reading this? Because I'm out of thing to try to solve this. 
If you need anything to clarify this issue, just ask I will provide it to you. Thank you for your time.

**Comment by lsmith77** [comment]
you likely have some sort of white space before the opening php tag. potentially this white space is not shown in your editor.

**Comment by ohFRY** [comment]
I've just deleted the file and created another _new_ one. I've typed the code instead of copy/paste it. The output is still the same. I'm using Notepad++ with an encode UTF-8.

But when I do in my Konsole:
**# cat -A src/Illustra/MainBundle/Security/User/Provider/FacebookProvider.php**
    M-oM-;M-?<?php^M$
    ^M$
    namespace Illustra\MainBundle\Security\User\Provider;^M$
    ^M$
    use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;^M$
    use Symfony\Component\Security\Core\Exception\UnsupportedUserException;^M$
...

_(the -A option is to --show-all)_

is this normal?

**Comment by lsmith77** [comment]
seems like notepad is screwing up your files. note this is not an issue related to this bundle. i recommend you find a different editor or try and search how to configure notepadd++ to not add windows line endings.

**Comment by ohFRY** [comment]
I thought it was related until you pointed out the problem. And I thank you for that.

**Comment by stof** [comment]
@akerz Using UF8 in Notepad++ adds a BOM which can break things. Use "UTF8 without BOM" as encoding.

**Comment by ohFRY** [comment]
@stof awesome ! thanks a lot! It works.
_... and sorry to have polluted this bundle page, I just didn't know where to find the solution._

**Comment by deepaliVats** [comment]
Whenever  I am create model using gii and use it create an error msg like that:
"Namespace declaration statement has to be the very first statement in the script"
Please some provide its exact solution for yii2

**Comment by ozgursoy** [comment]
@stof Thanks a lot, I handle it with nodepad++

**Comment by MartinGacheru** [comment]
The whitespace before php opening tag has to be removed i.e before <?php there should not be whitespace

**Comment by MartinGacheru** [comment]
The whitespace before php opening tag has to be removed i.e before <?php there should not be whitespace
