### ISSUE TITLE
Cookie is not removed after logout when appId is too big

### ISSUE THREAD

**Issue by althink** [FriendsOfSymfony/FOSFacebookBundle#73]
There is a small bug in FOS\FacebookBundle\Security\Logout\FacebookHandler:

``` php
$fb_cookie = sprintf(
            'fbsr_%d',
            $this->facebookApi->getAppId()
        );
```

This doesn't work right. For my appId: 208621755871551 returns fbsr_2147483647. Replacing %d with %s will fix it.

**Comment by schmittjoh** [comment]
Sounds good, can you make a PR?
