### ISSUE TITLE
Documentation for Custom User Provider unclear / wrong

### ISSUE THREAD

**Issue by michaelsauter** [FriendsOfSymfony/FOSFacebookBundle#77]
I found some unclear or wrong bits in the docs:
- It should be "Custom User Provider" instead of "Customer User Provider" ;)
- In the User model, the facebookID property needs to be persisted, so maybe add an example Doctrine annotation or at least say that the developer needs to take care of this
- In the User model, the serialize() and unserialize() methods try to access a property "facebookId" which should be "facebookID"

**Comment by lsmith77** [comment]
can you put together a PR with these fixes?
