### ISSUE TITLE
Latest FosFacebookBundle breaks Symfony 2.0.x compability

### ISSUE THREAD

**Issue by tarjei** [FriendsOfSymfony/FOSFacebookBundle#80]
Hi, I'm reporting this as an issue allthough I've seen the comments to the commit.

This issue manifests itself with the following error:
PHP Fatal error:  Call to undefined method Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension::addSecurityListenerFactory() in .../vendor/bundles/FOS/FacebookBundle/FOSFacebookBundle.php on line 25

Current workaround:

in deps.lock, add:

```
FOSFacebookBundle b3bfbfc2898d62ccb3ec697cafe32f374928d49c
```

and run bin/vendors install

**Comment by stof** [comment]
I have finally created the tag so simply use the 1.0.0 tag for Symfony 2.0
