### ISSUE TITLE
Call to undefined method Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension::addSecurityListenerFactory()

### ISSUE THREAD

**Issue by dupuchba** [FriendsOfSymfony/FOSFacebookBundle#83]
Hi everyone,

I am trying to install FOSFacebookBundle but once I install via github the bundle, I got this message on my webpage:

Call to undefined method Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension::addSecurityListenerFactory() in MyWebAppPath\vendor\bundles\FOS\FacebookBundle\FOSFacebookBundle.php on line 25

Someone has an idea???

Thank's everyone

**Comment by stof** [comment]
Please use the 2.0 branch for Symfony 2.0. The master branch is for Symfony 2.1 only now.
