### ISSUE TITLE
SecurityBundle and FosFacebookBundle

### ISSUE THREAD

**Issue by primozs** [FriendsOfSymfony/FOSFacebookBundle#85]
Hello
I am not sure if i have a compatibility problem between these two? SecurityBundle and FosFacebookBundle
I get this error just enabling the FosFacebookBundle

Call to undefined method Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension::addSecurityListenerFactory() 
in ...vendor/bundles/FOS/FacebookBundle/FOSFacebookBundle.php on line 25

Thanks for any ideas

**Comment by stof** [comment]
you need to use the 2.0 branch (or the tagged version which is the same currently) for Symfony 2.0. The master branch now requires Symfony master where the way to register factories changed

**Comment by primozs** [comment]
yes i just found the note on the FosFacebookBundle comments  
Thanks for quick reply!
Nice day
Primoz
