### ISSUE TITLE
Problem with security extension

### ISSUE THREAD

**Issue by lmammino** [FriendsOfSymfony/FOSFacebookBundle#86]
Recently i update all my vendors and i got this error:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension' does not have a method 'addSecurityListenerFactory' in /Applications/MAMP/htdocs/sbaam/vendor/bundles/JMS/SecurityExtraBundle/DependencyInjection/SecurityExtension.php line 86

I needed to disable the bundle (and comment its configuration on my config files) to continue the development. I hope a solution to come soon...

**Comment by lsmith77** [comment]
try to 2.0 branch in case you are using Symfony 2.0.x

**Comment by schmittjoh** [comment]
Yes, this method is not available on Symfony 2.0.x.
