### ISSUE TITLE
Access control path redirects to facebook application page

### ISSUE THREAD

**Issue by adityapatadia** [FriendsOfSymfony/FOSFacebookBundle#97]
Fosfacebook bundle is working perfect with facebook login but when I secure a path with access control, going to that path redirects to facebook application page instead showing /login page

**Comment by adityapatadia** [comment]
ok, solved it now. You just need to put your website url instead of facebook url in app_url parameter in security.yml

**Comment by lsmith77** [comment]
great. if you have any suggestions for how to improve the README .. please send us a pull request.

**Comment by adityapatadia** [comment]
i think this must be changed  in readme
fos_facebook:
                  app_url: "http://apps.facebook.com/appName/"
                  server_url: "http://localhost/facebookApp/"

This app_url must be same as server_url. The current configuration does not work.
